language: go

os:
  - linux

go:
  - 1.8

before_install:
  - cd indexcov && go get ./... ; cd ..
  - cd depth && go get ./... ; cd ..
script:
  - cd indexcov && bash functional-tests.sh ; cd ..
#- cd depth && bash functional-test.sh ; cd ..
